<?php

return [
    [
        'name'             => 'Configuration',
        'description'      => null,
        'url'              => '#',
        'type'             => 'Module',
        'order'            => 0,
        'icon'             => 'fa-cog',
        'is_active'        => 1,
        'is_shown_on_menu' => 1,
        'is_publicly_visible' => 0,
        'children' => [
            [
                'name'             => 'Module Manager',
                'description'      => null,
                'url'              => '/admin/modules',
                'type'             => 'Module',
                'order'            => 1,
                'icon'             => 'fa-user',
                'is_active'        => 1,
                'is_shown_on_menu' => 1,
                'is_publicly_visible' => 0,
                'children' => [
                    [
                        'name'             => 'List all modules',
                        'description'      => null,
                        'url'              => '/admin/modules',
                        'type'             => 'Page',
                        'order'            => 0,
                        'icon'             => 'fa-list',
                        'is_active'        => 1,
                        'is_shown_on_menu' => 1,
                        'is_publicly_visible' => 0,
                    ],
                    [
                        'name'             => 'Add modules',
                        'description'      => null,
                        'url'              => '/admin/modules/create',
                        'type'             => 'Page',
                        'order'            => 0,
                        'icon'             => 'fa-plus',
                        'is_active'        => 1,
                        'is_shown_on_menu' => 1,
                        'is_publicly_visible' => 0,
                    ],
                ]
            ],
            [
                'name'             => 'Widgets Manager',
                'description'      => null,
                'url'              => '/admin/widgets',
                'type'             => 'Module',
                'order'            => 2,
                'icon'             => 'fa-user',
                'is_active'        => 1,
                'is_shown_on_menu' => 1,
                'is_publicly_visible' => 0,
                'children' => [
                    [
                        'name'             => 'List all widgets',
                        'description'      => null,
                        'url'              => '/admin/widgets',
                        'type'             => 'Page',
                        'order'            => 0,
                        'icon'             => 'fa-list',
                        'is_active'        => 1,
                        'is_shown_on_menu' => 1,
                        'is_publicly_visible' => 0,
                    ],
                    [
                        'name'             => 'Add widgets',
                        'description'      => null,
                        'url'              => '/admin/widgets/create',
                        'type'             => 'Page',
                        'order'            => 0,
                        'icon'             => 'fa-plus',
                        'is_active'        => 1,
                        'is_shown_on_menu' => 1,
                        'is_publicly_visible' => 0,
                    ],
                ]
            ],
            [
                'name'             => 'User',
                'description'      => null,
                'url'              => '/admin/users',
                'type'             => 'Module',
                'order'            => 3,
                'icon'             => 'fa-user',
                'is_active'        => 1,
                'is_shown_on_menu' => 1,
                'is_publicly_visible' => 0,
                'children' => [
                    [
                        'name'             => 'List all user',
                        'description'      => null,
                        'url'              => '/admin/users',
                        'type'             => 'Page',
                        'order'            => 0,
                        'icon'             => 'fa-list',
                        'is_active'        => 1,
                        'is_shown_on_menu' => 1,
                        'is_publicly_visible' => 0,
                    ],
                    [
                        'name'             => 'Add user',
                        'description'      => null,
                        'url'              => '/admin/users/create',
                        'type'             => 'Page',
                        'order'            => 0,
                        'icon'             => 'fa-plus',
                        'is_active'        => 1,
                        'is_shown_on_menu' => 1,
                        'is_publicly_visible' => 0,
                    ],
                ]
            ],
            [
                'name'             => 'Group',
                'description'      => null,
                'url'              => '/admin/groups',
                'type'             => 'Module',
                'order'            => 4,
                'icon'             => 'fa-sign-in',
                'is_active'        => 1,
                'is_shown_on_menu' => 1,
                'is_publicly_visible' => 0,
                'children' => [
                    [
                        'name'             => 'List all group',
                        'description'      => null,
                        'url'              => '/admin/groups',
                        'type'             => 'Page',
                        'order'            => 0,
                        'icon'             => 'fa-list',
                        'is_active'        => 1,
                        'is_shown_on_menu' => 1,
                        'is_publicly_visible' => 0,
                    ],
                    [
                        'name'             => 'Add group',
                        'description'      => null,
                        'url'              => '/admin/groups/create',
                        'type'             => 'Page',
                        'order'            => 0,
                        'icon'             => 'fa-plus',
                        'is_active'        => 1,
                        'is_shown_on_menu' => 1,
                        'is_publicly_visible' => 0,
                    ],
                ]
            ],
        ]
    ],
];