<?php

return [
    [
        'name'             => 'Configuration',
        'url'              => '#',
        'type'             => 'Module',
        'order'            => 0,
        'icon'             => 'fa-cog',
        'is_active'        => 1,
        'is_shown_on_menu' => 1,    
    ],
    [
        'name'             => 'Module Manager',
        'url'              => '/admin/modules',
        'type'             => 'Module',
        'order'            => 1,
        'icon'             => 'fa-user',
        'is_active'        => 1,
        'is_shown_on_menu' => 1,
    ],
    [
        'name'             => 'List all modules',
        'url'              => '/admin/modules',
        'type'             => 'Page',
        'order'            => 0,
        'icon'             => 'fa-list',
        'is_active'        => 1,
        'is_shown_on_menu' => 1,
    ],
    [
        'name'             => 'Add modules',
        'url'              => '/admin/modules/create',
        'type'             => 'Page',
        'order'            => 0,
        'icon'             => 'fa-plus',
        'is_active'        => 1,
        'is_shown_on_menu' => 1,
    ],
    [
        'name'             => 'Widgets Manager',
        'url'              => '/admin/widgets',
        'type'             => 'Module',
        'order'            => 2,
        'icon'             => 'fa-user',
        'is_active'        => 1,
        'is_shown_on_menu' => 1,
    ],
    [
        'name'             => 'List all widgets',
        'url'              => '/admin/widgets',
        'type'             => 'Page',
        'order'            => 0,
        'icon'             => 'fa-list',
        'is_active'        => 1,
        'is_shown_on_menu' => 1,
    ],
    [
        'name'             => 'Add widgets',
        'url'              => '/admin/widgets/create',
        'type'             => 'Page',
        'order'            => 0,
        'icon'             => 'fa-plus',
        'is_active'        => 1,
        'is_shown_on_menu' => 1,
    ],
    [
        'name'             => 'User',
        'url'              => '/admin/users',
        'type'             => 'Module',
        'order'            => 3,
        'icon'             => 'fa-user',
        'is_active'        => 1,
        'is_shown_on_menu' => 1,
    ],
    [
        'name'             => 'List all user',
        'url'              => '/admin/users',
        'type'             => 'Page',
        'order'            => 0,
        'icon'             => 'fa-list',
        'is_active'        => 1,
        'is_shown_on_menu' => 1,
    ],
    [
        'name'             => 'Add user',
        'url'              => '/admin/users/create',
        'type'             => 'Page',
        'order'            => 0,
        'icon'             => 'fa-plus',
        'is_active'        => 1,
        'is_shown_on_menu' => 1,
    ],
    [
        'name'             => 'Group',
        'url'              => '/admin/groups',
        'type'             => 'Module',
        'order'            => 4,
        'icon'             => 'fa-sign-in',
        'is_active'        => 1,
        'is_shown_on_menu' => 1,
    ],
    [
        'name'             => 'List all group',
        'url'              => '/admin/groups',
        'type'             => 'Page',
        'order'            => 0,
        'icon'             => 'fa-list',
        'is_active'        => 1,
        'is_shown_on_menu' => 1,
    ],
    [
        'name'             => 'Add group',
        'url'              => '/admin/groups/create',
        'type'             => 'Page',
        'order'            => 0,
        'icon'             => 'fa-plus',
        'is_active'        => 1,
        'is_shown_on_menu' => 1,
    ],
];